### ISSUE TITLE
Evaluation of system 1 for text analysis

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#13]
We need to evaluate how system 1 works starting from the ground truth based on the ten SOWs provided by the customer.

**Comment by wmburke** [comment]
What is system 1? Is that the first algorithm that we've been using so far, understanding that system is the one that @asitang is currently working on?

**Comment by giuseppetotaro** [comment]
@wmburke, system 1 is the algorithm currently implemented and used for training the model and identifying the most suitable standard for the given text. Actually, system 1 is the technology that we reported in the [system diagram](https://github.com/nasa-jpl/ASSESS/blob/master/doc/assess_train.pdf). However, I and @asitang would like to use a different terminology from this point forward because we have only one system and we are working on it to improve its performance.
