### ISSUE TITLE
Threshold for search results

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#14]
# User Story

Threshold for Search Results

**Priority**: 1
**Estimate**: .03

## Description

**_As a_** end user

**_I want to_** only see suggested standards that are relevant to the text that I provided

**_so that_** I don't waste time reviewing standards that have a low likelihood of being relevant.

### Acceptance Criterion 1

**_Given_** a list of suggested standards returned from analysis of an uploaded document or pasted text

**_When_** I look at the relevancy scores on all of the standards

**_Then_** I only find scores that are 40% or greater.

## Notes

It's possible that 40% is not the right threshold number to set, but it seems like a good place to start. Of course, the actual number should depend on the research that is done to determine below what number there is nothing useful returned. This will depend on the algorithm, etc...

We should tend towards showing too much as opposed to not enough.

**Comment by wmburke** [comment]
I'm leaving this open until we resolve the discussion started here: https://github.com/nasa-jpl/ASSESS/issues/30#issuecomment-360589700

**Comment by giuseppetotaro** [comment]
@wmburke, this could include what we reported in #30. I would suggest to work on both threshold and pagination only when we will have more details.

**Comment by wmburke** [comment]
I'm fine with that on the pagination front, but threshold is mandatory - we can figure out what the number is as we refine it, but I see no reason the code shouldn't be in place.

From a user perspective, it is a waste of time to see a listing that includes thing with a 1% relevancy score.

**Comment by giuseppetotaro** [comment]
@wmburke, please write it as a user story so that we can start from that our discussion.

**Comment by wmburke** [comment]
@giuseppetotaro Please review the new user story, etc above and make sure that you like it. Happy for you to update it as you see fit.

**Comment by asitang** [comment]
stale
