### ISSUE TITLE
Improve our internal standards library (collect more data)

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#18]
We are currently using a model based on 2074 standards (2000 standards from IEEE and 74 standards from ISO). We could also use standards from ASTM (provided by the Customer), more IEEE standards and more ISO standards. Here are some information that I found out:
- **NASA standards**: 42 PDF documents collected from Web Archive;
- **IEEE standards**: top 2000 standards (only metadata and abstracts) in CSV format collected from IEEE Xplore website, but IEEE currently provides 7353 standards in total;
- **ASTM standards**: 132 PDF documents provided by the Customer, but the ASTM website provides more standards (although it looks like there is no way to easily export metadata as we did for IEEE standards);
- **ISO standards**: 74 standards (only metadata and scopes), but the ISO website provides 22353 standards in total.

Furthermore, I would like to discuss the information reported on the OODT wiki page "Data Collection" (I have already split the table in two sections: "Standards" and "Statement of Works (SOWs)").

**Comment by vlall** [comment]
We may need to focus on a broader set of standards than originally planned.

**Comment by asitang** [comment]
stale
