### ISSUE TITLE
Provide more context for what the score means

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#2]
.. and maybe it should be a 1-100 number?

**Comment by wmburke** [comment]
In addition, we should set a threshold below which we don't show anything because they clearly don't match.

**Comment by asitang** [comment]
@wmburke where should we provide this context? Will do it in the README for this repository. And I am guessing in some sort of Usage Document for this tool.

**Comment by wmburke** [comment]
I would put it in a hovertip on the page itself. I will do this during the next iteration of the design.

Tell me what you think the threshold for matching should be. Let's translate our 0-1 into a percentile so we can give scores like 83% relevance. We won't show anything below what? 30%? 50%? 70%? @asitang Give me your opinion - either now or after further testing with the model.

**Comment by wmburke** [comment]
The percent relevancy and not showing anything below a certain threshold is even more important if we're going to show recommended standards for individual sections within a document. In this case, there SHOULD be some sections that have NO recommended standards, and others that have quite a few. Otherwise, the amount of data to scroll through will be overwhelming.

**Comment by wmburke** [comment]
this was duplicated by #30 and #33
