### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#23]
# User Story

User documentation

**Priority**: 2
**Estimate**: 1

## Description

**_As a_** User

**_I want to_** have the high-level documentation of the system

**_so that_** I can use the system with confidence

### Acceptance Criterion 1

**_Given_** the URL to the website, and the home page includes the user documentation,

**_When_** I attempt to search for recommended standards related to the given text, following the step-by-step instructions,

**_Then_** the search operation should complete providing the results according to the expected output as shown in the documentation.

### Acceptance Criterion 2

**_Given_** the URL to the website, and the home page includes the user documentation,

**_When_** I attempt to search for recommended standards related to the uploaded document, following the step-by-step instructions,

**_Then_** the search operation should complete providing the results according to the expected output as shown in the documentation.

## Notes

The user documentation should be available on the website and GitHub.

**Comment by wmburke** [comment]
This is some impressive plan layout, @giuseppetotaro and @asitang. Nice work.
When you say available on the website and GitHub, are we talking about the exact same docs in both places? If so, where on Github? The wiki? Also, what is the rationale for this? If they are exactly the same, I'm not sure there's a need for duplication.

**Comment by giuseppetotaro** [comment]
@wmburke, providing a link to the GitHub wiki within the website could be an option.

**Comment by wmburke** [comment]
My goal is to make the interface dead simple and then provide some overview instructions as well. We can play this by ear as the interface comes together as far as I'm concerned.
