### ISSUE TITLE
Admin documentation

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#24]
# User Story

Admin documentation

**Priority**: 3
**Estimate**: 1

## Description

**_As a_** Administrator

**_I want to_** have the low-level documentation of the system

**_so that_** I can easily install the system on my own and train the model with the given standards

### Acceptance Criterion 1

**_Given_** the URL to the GitHub repository, that includes the admin documentation,

**_When_** I attempt to install the system, following the step-by-step instructions,

**_Then_** the installation procedure should complete successfully or provide details about the possible causes of failure.

### Acceptance Criterion 2

**_Given_** the URL to the GitHub repository, that includes the admin documentation,

**_When_** I attempt to add new standards to the model following the step-by-step instructions (whether there is a pre-existing model or not),

**_Then_** the training procedure should complete successfully or provide details about the possible causes of failure.

## Notes

The admin documentation should be available on GitHub
The admin documentation should include how to train and re-train the model with the given standards

**Comment by wmburke** [comment]
On Github in the wiki?

**Comment by wmburke** [comment]
Am I safe in assuming that the admin documentation should also include how to re-train the model given new standards? If so, I will add that to the User Story. If not, tell me where that should be added.

**Comment by giuseppetotaro** [comment]
@wmburke, the admin documentation should include also hoe to train and re-train the model. I modified the description of this user story accordingly.

**Comment by wmburke** [comment]
Thanks, @giuseppetotaro - I added a second Acceptance Criterion based on that. Feel free to tweak it if need be.

**Comment by asitang** [comment]
stale
