### ISSUE TITLE
Scientific documentation

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#25]
# User Story

Scientific documentation

**Priority**: 4
**Estimate**: 2

## Description

**_As a_** Technology expert 

**_I want to_** have the in-depth documentation of the system

**_so that_** I can understand the whole system from a scientific perspective

### Acceptance Criterion 1

**_Given_** the URL to the GitHub repository, that includes the scientific documentation,

**_When_** I read the technical and scientific details about the algorithms used to recommend standards

**_Then_** I should be able to summarize how the system determines the score of the search results

## Notes

The scientific documentation should be available on GitHub as one or more wiki pages

**Comment by wmburke** [comment]
wiki?

**Comment by giuseppetotaro** [comment]
@wmburke, I slightly modified the notes. Yes, I would provide the scientific documentation as one or more wiki pages.

**Comment by asitang** [comment]
stale
