### ISSUE TITLE
Organized data store

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#26]
# User Story

Organized data store

**Priority**: 2
**Estimate**: 1

## Description

**_As a_** Team member developing the ASSESS software

**_I want to_** have a network folder available 

**_so that_** I can easily store and retrieve the standard documents

### Acceptance Criterion 1

**_Given_** the URI to the datastore

**_When_** I attempt to locate a standard document used to train the model

**_Then_** I should be able to retrieve the document and save it on my computer

## Notes

Standard documents are not stored yet within the original folder on `memex.dyndns.org`.

**Comment by wmburke** [comment]
Is this intended to be part of the ASSESS system or just part of our internal organization for developing ASSESS?

**Comment by giuseppetotaro** [comment]
@wayne, this is intended to be part of our internal organization as a sort of temporary store for the standard documents. We will figure out later how to organize the data for the users.
