### ISSUE TITLE
Provide more info about standards

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#3]
For example, we should provide separate fields for the standards organization, the number of the standard and the name of the standard, where possible. Right now, it's just all in a single title, some of which seem to be the name of the file, not the name of the standard, eg E2851E2851M-13 Standard Specification for Ruggedness Requirements for HAZMAT Instrumentation.pdf.json

**Comment by wmburke** [comment]
This is also intended to be on the recommended standards.

**Comment by asitang** [comment]
Right now we are just reading the files directly, extracting the text and doing analysis, hence we are using the filename as the Standard name. We just need a mapping for these files to the standard names etc. Once we have access to IHS or have crawled a big repository we will have all the information in say a csv file with name, number etc. Then it will be easier to provide those details. Right now it is possible for the IEEE standards we have.

**Comment by wmburke** [comment]
duplicated as #32
