### ISSUE TITLE
Search results in pages

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#30]
# User Story

Search results in pages

**Priority**: 4
**Estimate**: 1

## Description

**_As a_** User 

**_I want to_** see the search results organized in pages 

**_so that_** I can easily explore the recommended standards

### Acceptance Criterion 1

**_Given_** a number of search results

**_When_** I use 10 as a value for the number of results per page

**_Then_** the system should provide a number of pages equal to the ceiling of the number of search results divided by 10

### Acceptance Criterion 2

**_Given_** a number of search results

**_When_** I use 25 as a value for the number of results per page

**_Then_** the system should provide a number of pages equal to the ceiling of the number of search results divided by 25

### Acceptance Criterion 3

**_Given_** a number of search results

**_When_** I use 50 as a value for the number of results per page

**_Then_** the system should provide a number of pages equal to the ceiling of the number of search results divided by 50

**Comment by wmburke** [comment]
If we think there will be that many standards returned, then this is a good idea.
My suggestion on #14 was NOT however for pagination or for giving the user the ability to determine the threshold for what is show to them. It was for us to make that determination. If the similarity between a piece of text and a standard is 1%, what is the value in pretending that there is enough similarity there for them to consider it?

I don't know where the threshold should be however - maybe around 40%? That's what I wanted to get out of #14.

**Comment by giuseppetotaro** [comment]
Thanks @wmburke. Currently, this user story has a very low priority but we can switch it to an open question so that we will work on it only when we will have a better understanding of the problem.

**Comment by wmburke** [comment]
I'm fine with that, @giuseppetotaro - we can table the part about pagination. In fact, that will likely come out as part of the UI development and so may not need a separate issue for now.

Where will we cover the implementation of a minimum threshold below which we show no matches? That could be #14, although we will need to add the User Story into it. Let me know if you agree and I'll be happy to do that.

**Comment by giuseppetotaro** [comment]
@wmburke, I agree that the user story related the threshold below which we show no matches should be created or added to #14, that is currently an open question. Please refer to the [guidelines](https://github.com/nasa-jpl/ASSESS/blob/master/.github/CONTRIBUTING.md) and the [template](https://github.com/nasa-jpl/ASSESS/blob/master/.github/ISSUE_TEMPLATE.md) for contributing. By the way, all user stories in progress are revised at the end of each iteration.

**Comment by asitang** [comment]
stale
