### ISSUE TITLE
Ground truth and first evaluation

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#31]
# User Story

Ground truth and first evaluation

**Priority**: 1
**Estimate**: 2

## Description

**_As a_** Team member working on development of the software

**_I want to_** build a Ground Truth dataset 

**_so that_** I can perfom the first evaluation of the system

### Acceptance Criterion 1

**_Given_** the 10 SoWs provided by the Customer

**_When_** I extract the relevant text from the given SoWs, 
and manually search for the related standards among the documents used for training the model

**_Then_** I should have a JSON-formatted Ground Truth for performing the first evaluation of the system

### Acceptance Criterion 2

**_Given_** the Ground Truth based on the 10 SoWs provided by the Customer

**_When_** I attempt to search for the recommended standards for each SoW

**_Then_** I should have a list of search results to compare with expected results from the Ground Truth

## Notes

Supervision from the Customer
10 SoWs provided by the Customer

**Comment by wmburke** [comment]
So the goal here is to build a ground truth dataset, and then be able to utilize it to show that our matching algorithm works properly, correct?

**Comment by giuseppetotaro** [comment]
@wmburke, it is correct. We need it to measure the performance of our system and understand how to improve it.

**Comment by wmburke** [comment]
+1 - I changed the **As a** to make it a little more clear then. Thanks!

**Comment by asitang** [comment]
stale
