### ISSUE TITLE
Display information about standards

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#32]
# User Story

Display information about standards

**Priority**: 1
**Estimate**: 1

## Description

**_As a_** User 

**_I want to_** see more information within the search results 

**_so that_** I can know more details about the recommended standards

### Acceptance Criterion 1

**_Given_** the running system

**_When_** I upload a document to the system

**_Then_** I should obtain a list of search results, each of which including standard organization, identifier and name

### Acceptance Criterion 2

**_Given_** the running system

**_When_** I submit a plain text to the system

**_Then_** I should obtain a list of search results, each of which including standard organization, identifier and name

**Comment by wmburke** [comment]
I'd like to add in here that it should also include a link to where the standard can be acquired as well as an accordion section to display the abstract (or similar) right on the page.

This may change based on some ui designing...

**Comment by giuseppetotaro** [comment]
@wayne, the ability to provide a link is included in #34 and #35.

**Comment by asitang** [comment]
stale
