### ISSUE TITLE
Original link to recommended standards

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#34]
# User Story

Original link to recommended standards

**Priority**: 1
**Estimate**: 1

## Description

**_As a_** User 

**_I want to_** have the original link to the standard 

**_so that_** I can visit the web page of the recommended standard

### Acceptance Criterion 1

**_Given_** the search results from the running system

**_When_** I click on the original link for a standard

**_Then_** I should be able to visit the web page of the recommended standard

**Comment by wmburke** [comment]
Your acceptance criterion are a bit limiting in that it does not account for any other than the 4 sources of standards that we are currently working with. I would change this so that it is one generic acceptance criterion instead.

**Comment by giuseppetotaro** [comment]
@wmburke, I changed so that is is one generic acceptance criterion. However, I would be more specific once we have the list of standard organizations from which we collected the documents used for training.

**Comment by wmburke** [comment]
But we won't know all of the standard organizations from which standards will be contributed in the future. Be able to do this independent of the standard org is very important. Please tell me if I'm missing something.

**Comment by asitang** [comment]
stale
