### ISSUE TITLE
Internal link to recommended standards

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#35]
# User Story

Internal link to recommended standards

**Priority**: 4
**Estimate**: 2

## Description

**_As a_** User 

**_I want to_** have an internal link to the standard 

**_so that_** I can visit the cached version of the web page of the recommended standard

### Acceptance Criterion 1

**_Given_** the search results from the running system

**_When_** I click on the internal link to a ISO standard

**_Then_** I should be able to visit the cached version of the web page of the recommended standard

### Acceptance Criterion 2

**_Given_** the search results from the running system

**_When_** I click on the internal link to a NASA standard

**_Then_** I should be able to visit the cached version of the web page of the recommended standard

### Acceptance Criterion 3

**_Given_** the search results from the running system

**_When_** I click on the internal link to a IEEE standard

**_Then_** I should be able to visit the cached version of the web page of the recommended standard

### Acceptance Criterion 4

**_Given_** the search results from the running system

**_When_** I click on the internal link to a ASTM standard

**_Then_** I should be able to visit the cached version of the web page of the recommended standard

**Comment by wmburke** [comment]
I think you should also have only generic acceptance criteria here as well - it shouldn't matter where the standards come from. You could genericize it by adding in "if avaiable" or something like that.

**Comment by giuseppetotaro** [comment]
@wmburke, I agree. It should not matter where the standards come from. This is the reason why the acceptance criteria have been written in order to cover all the possible cases, assuming that we are working with standards from those organizations.
