### ISSUE TITLE
When you upload a file, it should let you know that it has been done

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#4]
For example, it should tell you the name of the file that was uploaded

**Comment by giuseppetotaro** [comment]
Hi @wmburke, actually the file is uploaded only when the user submits a request to get standards through "Get Standards" button. Currently, the user can select the file through "Choose a file" button and then upload and extract content through "Get Standards" button. Therefore, I have added a javascript function that provides a message and the filename once a file has been selected by user (Commit aaea12865a64f16cc34ffb9b801749dc66410a07).
You can find in attachment what it is showed after the alert message within a specific <div> container.
Please let me know if this may solve the issue.
<img width="1361" alt="screen shot 2017-09-29 at 9 40 47 am" src="https://user-images.githubusercontent.com/8323664/31026209-6d4688a4-a4fa-11e7-9029-9be990420ae5.png">

**Comment by wmburke** [comment]
Awesome! Great work, Giuseppe! Thank you.
