### ISSUE TITLE
Fix Security Alerts

### ISSUE THREAD

**Issue by vlall** [nasa-jpl/ASSESS#45]
The `requirements.txt` vulnerabilities need to be upgraded. This is a simple task. 

Here are the current dependency vulnerabilities:
- urllib3
   **high severity**
- Jinja2
   **high severity**
- flask 
  **moderate severity**
- requests
   **moderate severity**

**Comment by vlall** [comment]
This should be fixed with this commit: https://github.com/nasa-jpl/ASSESS/commit/5e3db82d0895835cc23cb4dbb623eefb59098a45

**Comment by HenryJiao** [comment]
numpy 1.12.1 is not secure, updated it to 1.16.4 and also updated requests to 2.22.0

In a side note, I removed Werkzeug==0.12.2 from requirements.txt as it is part of Flask and was causing a bug where functions were overlapping
