### ISSUE TITLE
Provide API docs

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#5]
The API section in the webUI is sparse and awaiting content.

**Comment by giuseppetotaro** [comment]
Hi @wmburke, I have just added a short description of `/predict` (commit 5e1134f02ef3cc0f2d49f03657abab5ddf767028), that is the API for extracting standards references and suitable standards from text. By the way, @asitang provided also an API named `/train` to train the model from documents into the `ASSESS/webapp/standards` sub-folder. However, we could provide more documentation about that API later.

**Comment by wmburke** [comment]
Thanks, @giuseppetotaro - I think that's great for now. When we get in deeper, we can revisit this.
