### ISSUE TITLE
Upload collections of documents

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#6]
The tool should be able to accept individual documents as it currently does (SoWs, RFQs, etc...) or collections of documents (zip files most likely - not sure what else).

These collections once uploaded should be extracted, parsed individually to create the normal reports, as well as creating a summary report of all of the documents.

**Comment by giuseppetotaro** [comment]
@wmburke, thank you very much for this great suggestion. I sketched below an example of page where we can report the results of analysis against ZIP archive. Basically, we can report a summary containing a link for each document analyzed and subsequently a box including the results for each SoW. Does it make sense?

![assess_archive_mockup](https://user-images.githubusercontent.com/8323664/31786580-de384c32-b4bd-11e7-94cf-bfb4d2d08c97.png)

**Comment by wmburke** [comment]
That is excellent, @giuseppetotaro! I love it!

A few additions and tweaks:
1. I would only return a summary of the analyzed documents on the webpage, with the ability to download a zip file containing a full report of the analysis plus all of the individual reports for each document. I just think it will be too much info to be useful in a linear scrolling manner.
2. The returned summary should also include a collated list of all standards referenced in the documents and how many documents referenced each standard.
3. The full report on the analysis should include the returned summary plus:
   - a listing of the documents by referenced standard to make it easy to identify all docs that referenced a given standard
   - a listing of the recommended standards, ordered by some algorithm that takes into frequency of recommendation and relevance to the documents
   - a listing of all documents by recommended standard

What do you think about that?

**Comment by giuseppetotaro** [comment]
@wmburke I think these are great ideas. Let's start from enabling the upload and the analysis of a collection of documents and then we will move towards all these additions. Once we get the ability to upload a collection, I think we should create an issue for each addition and work on it.
Thanks a lot.

**Comment by giuseppetotaro** [comment]
Tika is already able to [recursively parse](https://tika.apache.org/1.17/api/org/apache/tika/parser/RecursiveParserWrapper.html) a container file, therefore we just need to test it and handle the results when a user submits a collection of documents, for instance, within a zipped archive.

**Comment by wmburke** [comment]
@giuseppetotaro Why is this a question instead of a story? Should I write the story?

**Comment by asitang** [comment]
stale
