### ISSUE TITLE
Build admin dashboard

### ISSUE THREAD

**Issue by wmburke** [nasa-jpl/ASSESS#7]
This should enable viewing and updating the standards used to train the model, as well as analytics for application usage by the end users (consider [piwik](https://piwik.org/) or [senssoft](https://senssoft.apache.org/) for this capability).

**Comment by wmburke** [comment]
@giuseppetotaro I think this is actually 3 tasks, based on our other discussions: #27 (Standards Index and Dashboard), a new one that you suggested in the discussion on #27 to make a separate task for statistics, and a new one to add analytics to the program via Piwik or SensSoft.

Are we in agreement? If so, I'll get all of that done.

**Comment by wmburke** [comment]
@giuseppetotaro - just checking in here. Are we in agreement with the above comment? If so, I'll get the three issues laid out.

**Comment by asitang** [comment]
stale
