### ISSUE TITLE
Preview of the parsed document

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#8]
# User Story

\<User story title\>

**Priority**: 2
**Estimate**: 2

## Description

**_As a_** User 

**_I want to_** see the preview of the parsed text 

**_so that_** I can select specific parts of the document for searching

### Acceptance Criterion 1

**_Given_** the running system

**_When_** I upload a document to the system

**_Then_** I should be able to select the plain text extracted for searching recommended standards

## Notes

We need a system where we can show the whole text extracted from the parsed document and then let the user select the piece of text for searching the most suitable standards. The text already selected by the system should be highlighted (e.g., scope, purpose, introduction, etc) so that the user can confirm or change the automatic selection performed by the system.

**Comment by asitang** [comment]
stale
