### ISSUE TITLE
Automatic extraction of standard references

### ISSUE THREAD

**Issue by giuseppetotaro** [nasa-jpl/ASSESS#9]
# User Story

Automatic extraction of standard references

**Priority**: 2
**Estimate**: 1

## Description

**_As a_** Team member 

**_I want to_** use Tika server 

**_so that_** I can extract text and metadata from standards and SoWs

### Acceptance Criterion 1

**_Given_** a running instance of Tika server

**_When_** I submit to Tika server a PDF document

**_Then_** I should have a JSON-formatted data structure made of the parsed text and metadata including standard references

### Acceptance Criterion 2

**_Given_** a running instance of Tika server

**_When_** I submit to Tika server a Word document

**_Then_** I should have a JSON-formatted data structure made of the parsed text and metadata including standard references

## Notes

Currently, Tika server is not enabled to use a specific `ContentHandler`, but I have already started to work on this new feature (there is an open thread on the mailing list `dev@tika.apache.org` named as "[DISCUSS] Enable specific ContentHandler for tika-server").

**Comment by wmburke** [comment]
How are we doing this now?

**Comment by giuseppetotaro** [comment]
@wmburke, we currently start a new process for each request for extracting text and metadata from the document/text. Having a separate component (i.e., Tika server) that works for extracting text and metadata could allow more flexibility and better performance.
